# Generated by Django 4.0.3 on 2022-04-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userprofile',
            new_name='profile',
        ),
    ]
