# Generated by Django 4.0.3 on 2022-04-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_comments_likes_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(),
        ),
    ]
