# Generated by Django 4.0.3 on 2022-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='insta.userprofile'),
        ),
    ]
